Models/ErrorViewModel.cs
using System;

namespace Examen_T3.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Nota.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Examen_T3.Models
{
    public class Nota
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ContentNote { get; set; }
        public string DateUpdate { get; set; }
    }
}

Controllers/HomeController.cs
using Examen_T3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Examen_T3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/NotasController.cs
using Examen_T3.DB;
using Examen_T3.Models;
using Examen_T3.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Examen_T3.Controllers
{
    public class InfoNotes
    {
        public Nota note { get; set; }
        public string info { get; set; }
    }

    public class NotasController : Controller
    {
        private NotesContext context;
        private INotaRepository repository;

        public NotasController(NotesContext context, INotaRepository repository)
        {
            this.context = context;
            this.repository = repository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var notes = GetInfNotes();
            return View("Index", notes);
        }
        [HttpGet]
        public IActionResult MuestraNota(int id)
        {
            var note = repository.GetNotes().FirstOrDefault(n => n.Id == id);
            return View("ViewNota", note);
        }
        [HttpGet]
        public IActionResult NewNote()
        {
            return View();
        }
        [HttpPost]
        public IActionResult NewNote(Nota note)
        {
            DateTime date = new DateTime();
            note.DateUpdate = date.ToString("dd,MMM,yyyy");

            repository.RegisterNote(note);

            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult DeleteNote(int id)
        {
            repository.DeleteNote(repository.GetNotes().FirstOrDefault(n => n.Id == id));
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult UpdateNote(int id)
        {
            Nota note = repository.GetNotes().FirstOrDefault(n => n.Id == id);

            return View("UpdateNote",note);
        }
        [HttpPost]
        public IActionResult UpdateNote(Nota note)
        {
            DateTime date = new DateTime();
            note.DateUpdate = date.ToString("dd,MMM,yyyy");

            note.DateUpdate = ReturnDate();

            repository.UpdateNote(note);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Search(string Search)
        {
            var notes = repository.SearchNote(Search);

            return View("SearchResult", notes);
        }



        private string Return50C(String cadena)
        {
            string newCadena = "";
            if (cadena.Length <= 50)
                return cadena;
            else
            {
                for (int i = 0; i < 50; i++)
                {
                    newCadena += cadena[i].ToString();
                }
                return newCadena;
            }

        }
        private List<Nota> GetInfNotes(){
            var notes = repository.GetNotes().ToList();
            //var notes = context.Notes.ToList();
            Nota infNote;
            List<Nota> notesList = new List<Nota>();


            foreach (Nota nota in notes)
            {
                infNote = new Nota()
                {
                    Id = nota.Id,
                    Title = nota.Title,
                    ContentNote = Return50C(nota.ContentNote)
                };
                notesList.Add(infNote);
            }
            return notesList;
        }

        private string ReturnDate()
        {
            DateTime date = new DateTime();

            return date.ToString("dd,MMM,yyyy"); ;

        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Notas/Index.cshtml
<head>
    <link rel="stylesheet" href="~/css/MuestraCursosEstilos.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title>Cursos</title>
    <style>
        .pos-buscador {
            top: -5rem;
            position: relative;
        }

        .contiene-mensaje {
            width: 50%;
            top: 3rem;
            height: 5rem;
            position: relative;
        }

        .opciones {
        }
    </style>
</head>
<!--<body style="background: rgb(59,59,80)">-->
<body>
    <div class="container">
    </div>
    <hr id="Separador-cab " /><br />
    <div>
        <p class="mensaje-secundario">Notas Registradas</p>
        <form asp-controller="Notas" asp-action="Search" method="post">
            <input type="search" placeholder="Buscar" id="Search" name="Search"/>
            <button>Buscar</button>
        </form>
    </div>
    <div id="contieneCursos">
        <div class="Cursos-mos">
            @foreach (Nota note in Model)
            {
                <div class="caja">
                    <div class="card">
                         <div>
                            <a class="text-decoration-none text-muted" href="Notas/MuestraNota?id=@note.Id"><h1 class="fs-5">@note.Title</h1></a>
                            <p id="ini">@note.ContentNote</p>
                         </div>    
                    </div>
                </div>
            }
        </div>
    </div>

</body>

Views/Notas/NewNote.cshtml
<div>
    <form asp-controller="Notas" asp-action="NewNote" method="post">
        <div class="mb-3">
            <label for="Title" class="form-label">Email address</label>
            <input type="text" class="form-control" id="Title" name="Title" placeholder="Title Note">
        </div>
        <div class="mb-3">
            <label for="ContentNote" class="form-label">Contenido </label>
            <textarea class="form-control" id="ContentNote" name="ContentNote" rows="3"></textarea>
        </div>
        <button type="submit">Crear</button>
    </form>
</div>

Views/Notas/RegisterNotes.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Notas/SearchResult.cshtml
<head>
    <link rel="stylesheet" href="~/css/MuestraCursosEstilos.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title>Cursos</title>
    <style>
        .pos-buscador {
            top: -5rem;
            position: relative;
        }

        .contiene-mensaje {
            width: 50%;
            top: 3rem;
            height: 5rem;
            position: relative;
        }

        .opciones {
        }
    </style>
</head>
<!--<body style="background: rgb(59,59,80)">-->
<body>
    <div class="container">
    </div>
    <hr id="Separador-cab " /><br />
    <div id="contieneCursos">
        <div class="Cursos-mos">
            @foreach (Nota note in Model)
            {
                <div class="caja">
                    <div class="card">
                        <div>
                            <a class="text-decoration-none text-muted" href="Notas/MuestraNota?id=@note.Id"><h1 class="fs-5">@note.Title</h1></a>
                            <p id="ini">@note.ContentNote</p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

</body>

Views/Notas/UpdateNote.cshtml
<div>
    <form asp-controller="Notas" asp-action="UpdateNote" method="post">
        <input type="hidden" id="Id" name="Id" value="@Model.Id"/>
        <div class="mb-3">
            <label for="Title" class="form-label">Email address</label>
            <input type="text" class="form-control" id="Title" name="Title" placeholder="Title Note" value="@Model.Title">
        </div>
        <div class="mb-3">
            <label for="ContentNote" class="form-label">Contenido </label>
            <textarea class="form-control" id="ContentNote" name="ContentNote" rows="3">@Model.ContentNote</textarea>
        </div>
        <button type="submit">Actualizar</button>
    </form>
</div>

Views/Notas/ViewNota.cshtml
<div>
    <div class="caja">
        <div class="card">
            <div>
                <a class="text-decoration-none text-muted" href="Notas/MuestraNota?id=@Model.Id"><h1 class="fs-5">@Model.Title</h1></a>
                <p id="ini">@Model.ContentNote</p>
                <p>@Model.DateUpdate</p>
            </div>
            <div>
                <a href="UpdateNote?id=@Model.Id" class="btn btn-info">Editar</a>
                <a href="DeleteNote?id=@Model.Id" class="btn btn-danger">Eliminar</a>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Examen_T3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Notas" asp-action="Index">Examen_T3</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Notas" asp-action="NewNote">Crear Nota</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Examen_T3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>